source "https://api.berkshelf.com"

cookbook 'redmine2',         github: "OpsDeliver/redmine2-cookbook"
# cookbook 'redmine2',       path: "/vagrant/Cookbooks/redmine2-cookbook"
cookbook 'rbenv',            github: "fnichol/chef-rbenv"
cookbook 'database',         '>= 2.3.0'
cookbook 'mysql',            '>= 5.2.12'
cookbook 'networking_basic', '>= 0.0.7'
cookbook 'yum',              '>= 3.2.0'
cookbook 'yum-epel',         '>= 0.3.6'
