---
driver:
  name: vagrant

provisioner:
  name: chef_solo

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
  - name: centos-6.5
    driver_config:
      box: opscode-centos-6.5
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
  - name: default
    run_list: [
      "recipe[zabbix-custom::default]",
	    "recipe[apache2::default]",
	    "recipe[apache2::mod_php5]",
	    "recipe[database::mysql]",
	    "recipe[mysql::server]",
	    "recipe[mysql::client]",
	    "recipe[mysql-custom::default]",
	    "recipe[zabbix]",
	    "recipe[zabbix::database]",
	    "recipe[zabbix::server]",
	    "recipe[zabbix::web]",
	    "recipe[zabbix-custom::japanese_font]"
		]
    attributes: {
		  "mysql": {
  		  "server_root_password": "serverrootpassword"
		  },
		  "zabbix": {
		    "server": {
		      "version": "2.4.0"
		    },
		    "agent": {
		      "version": "2.4.0",
		      "servers": ["localhost"]
		    }
		  }
    }
