source "https://api.berkshelf.com"

cookbook 'zabbix',          github: "OpsDeliver/zabbix"
# cookbook 'zabbix',        path: "/vagrant/Cookbooks/zabbix"
cookbook 'zabbix-custom',   github: "OpsDeliver/zabbix-custom"
# cookbook 'zabbix-custom', path: "/vagrant/Cookbooks/zabbix-custom"
cookbook 'mysql',           '>= 5.2.12'
cookbook 'mysql-custom',    github: "OpsDeliver/mysql-custom"
# cookbook 'mysql-custom',  path: '/vagrant/Cookbooks/mysql-custom'
cookbook 'yum-epel',        '>= 0.3.6'
cookbook 'yum',             '>= 3.2.0'
cookbook 'apache2',         github: "OpsDeliver/apache2"
# cookbook 'apache2',       path: "/vagrant/Cookbooks/apache2"
