source "https://api.berkshelf.com"

cookbook 'eccube',     github: "OpsDeliver/eccube"
# cookbook 'eccube',   path: "/vagrant/Cookbooks/eccube"
cookbook 'mysql',      '>= 5.2.12'
cookbook 'apache2',    github: "OpsDeliver/apache2"
# cookbook 'apache2',  path: "/vagrant/Cookbooks/apache2"
cookbook 'database',   '>= 2.2.0'
cookbook 'php',        '>= 1.4.6'
